# Reference:- TS 29.531 R16.0.0., Section- 6.1.6 Data Model 
info:
  version: 1.4.0
  description: OAI-NSSF Release v1.4.0
configuration:
  nsiInfoList:
    - snssai:
        sst: 128
        sd: '128'
      nsiInformationList:
        nrfId: http://192.168.70.136:8080/nnrf-disc/v1/nf-instances
        nsiId: '11'
    - snssai:
        sst: 1
      nsiInformationList:
        nrfId: http://192.168.70.136:8080/nnrf-disc/v1/nf-instances
        nsiId: '12'
    - snssai:
        sst: 130
        sd: '130'
      nsiInformationList:
        nrfId: http://192.168.70.137:8080/nnrf-disc/v1/nf-instances
        nsiId: '12'
    - snssai:
        sst: 222
        sd: '123'
      nsiInformationList:
        nrfId: http://oai-cn5g-nrf-10.fr:8080/nnrf-disc/v1/nf-instances
        nsiId: '11'
    - snssai:
        sst: 130
      nsiInformationList:
        nrfId: http://oai-cn5g-nrf-20.fr:8080/nnrf-disc/v1/nf-instances
        nsiId: '20'
        nrfNfMgtUri: http://oai-cn5g-nrf-10.fr:8080/nnrf-nfm/v1/nf-instances
    - snssai:
        sst: 131
        sd: '131'
      nsiInformationList:
        nrfId: http://oai-cn5g-nrf-20.fr:8080/nnrf-disc/v1/nf-instances
        nsiId: '20'
    - snssai:
        sst: 132
        sd: '132'
      nsiInformationList:
        nrfId: http://oai-cn5g-nrf-20.fr:8080/nnrf-disc/v1/nf-instances
        nsiId: '20'
    - snssai:
        sst: 133
      nsiInformationList:
        nrfId: http://oai-cn5g-nrf-20.fr:8080/nnrf-disc/v1/nf-instances
        nsiId: '20'
  taInfoList:
    - tai:
        plmnId:
          mcc: '208'
          mnc: '95'
        tac: '33456'
      supportedSnssaiList:
      - sst: 222
        sd: '123'
      - sst: 128
  amfInfoList:
    - targetAmfSet: oai5gcn.mcc208.mnc95.regionid128.setid1.3gppnetwork.org
      nrfAmfSet: http://oai-cn5g-nrf.fr:8080/nnrf-disc/v1/nf-instances'
      nrfAmfSetNfMgtUri: http://oai-cn5g-nrf.fr:8080/nnrf-nfm/v1/nf-instances
      amfList:
        - nfId: 405e8251-cc5a-45dd-a494-efb9eaf1cd58
          supportedNssaiAvailabilityData:
              tai:
                plmnId:
                  mcc: 208
                  mnc: 95
                tac: 33456
              supportedSnssaiList:
                - sst: 128
                  sd: 128
                - sst: 1
                - sst: 130
                  sd: 130
        - nfId: 405e8251-cc5a-45dd-a494-efb9eaf1cd68
          supportedNssaiAvailabilityData:
              tai:
                plmnId:
                  mcc: 208
                  mnc: 95
                tac: 33457
              supportedSnssaiList:
                - sst: 130
                - sst: 131
                  sd: 131
              taiList:
                - tai:
                    plmnId:
                      mcc: 208
                      mnc: 95
                    tac: 33458
                  supportedSnssaiList:
                    - sst: 132
                      sd: 132
    - targetAmfSet: oai5gcn.mcc208.mnc95.regionid128.setid2.3gppnetwork.org
      nrfAmfSet: http://oai-cn5g-nrf.fr:8080/nnrf-disc/v1/nf-instances
      nrfAmfSetNfMgtUri: http://oai-cn5g-nrf.fr:8080/nnrf-nfm/v1/nf-instances
      amfList:
        - nfId: 405e8251-cc5a-45dd-a494-efb9eaf1cd78
          supportedNssaiAvailabilityData:
              tai:
                plmnId:
                  mcc: 208
                  mnc: 95
                tac: 33460
              supportedSnssaiList:
                - sst: 133
